Fix the leaderboard calculation for the case where there is no confirmed mode
So we check to see whether `mode_confirm` exists before accessing it.

Without the fix, we get the error

```
  File "/Users/kshankar/e-mission/e-mission-server/emission/core/wrapper/tiersys.py", line 194, in updateTiers
    updated_user_tiers = self.computeRanks(last_ts, 3)
  File "/Users/kshankar/e-mission/e-mission-server/emission/core/wrapper/tiersys.py", line 158, in computeRanks
    val = User.computeConfirmed(user_id)[2]
  File "/Users/kshankar/e-mission/e-mission-server/emission/core/wrapper/user.py", line 333, in computeConfirmed
    invalid_replacement = ct_df_confirmed.user_input.apply(lambda ui: ui["mode_confirm"] == "pilot_ebike" and ("replaced_mode" not in ui or ui["replaced_mode"] == "pilot_ebike" or ui["replaced_mode"] == "same_mode"))
  File "/Users/kshankar/miniconda-4.8.3/envs/emission/lib/python3.7/site-packages/pandas/core/series.py", line 4200, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2388, in pandas._libs.lib.map_infer
  File "/Users/kshankar/e-mission/e-mission-server/emission/core/wrapper/user.py", line 333, in <lambda>
    invalid_replacement = ct_df_confirmed.user_input.apply(lambda ui: ui["mode_confirm"] == "pilot_ebike" and ("replaced_mode" not in ui or ui["replaced_mode"] == "pilot_ebike" or ui["replaced_mode"] == "same_mode"))
KeyError: 'mode_confirm'
```

With the fix, the `make_tiersys` command runs successfully