🧪 New single day tests for the multi-ooo case
These are the three days with multi-OOO, as outlined in
https://github.com/e-mission/e-mission-docs/issues/1122#issuecomment-2760212688

```
11654  2024-08-06T18:12:44.062398-07:00  2024-08-07T01:12:50.657156+00:00
11655  2024-08-06T17:49:19.433151-07:00  2024-08-07T01:17:57.419571+00:00
11656  2024-08-06T18:17:46.083736-07:00  2024-08-07T01:17:58.133647+00:00

17821  2024-08-11T12:07:58.998079-07:00  2024-08-11T19:08:00.778431+00:00
17822  2024-08-11T12:07:36.229032-07:00  2024-08-11T22:10:40.929623+00:00
17823  2024-08-11T15:07:23.980738-07:00  2024-08-11T22:10:41.666903+00:00

88477  2024-09-23T08:31:10.863754-07:00  2024-09-23T15:31:12.463861+00:00
88478  2024-09-23T08:26:29.936970-07:00  2024-09-23T22:01:45.836082+00:00
88479  2024-09-23T15:06:47.857451-07:00  2024-09-23T22:07:02.619321+00:00
```

These help us provide an MRE to test our solutions against, and to ensure that
future changes don't cause regressions.

Testing done:
I have verified that loading one of the MREs and running the pipeline fails in
the same way as https://github.com/e-mission/e-mission-docs/issues/1122

```
kshankar-41872s:gis_branch_tests kshankar$ ./e-mission-py.bash bin/debug/load_timeline_for_day_and_user.py /tmp/multi_ooo_aug_6_2024 test_aug_6
Config file not found, returning a copy of the environment variables instead...
Retrieved config: {'DB_HOST': 'mongodb://localhost:27017/openpath_stage', 'DB_RESULT_LIMIT': None, 'USE_HINTS': 'True'}
Connecting to database URL mongodb://localhost:27017/openpath_stage
/tmp/multi_ooo_aug_6_2024
Loading file /tmp/multi_ooo_aug_6_2024

$ ./e-mission-py.bash bin/debug/intake_single_user.py -e test_aug_6
Config file not found, returning a copy of the environment variables instead...
Retrieved config: {'DB_HOST': 'mongodb://localhost:27017/openpath_stage', 'DB_RESULT_LIMIT': None, 'USE_HINTS': 'True'}
Connecting to database URL mongodb://localhost:27017/openpath_stage
Trying to open debug.conf.json
INFO:root:NOMINATIM_QUERY_URL: None
Nominatim Query URL Configured: None
Nominatim URL not configured, place decoding must happen on the client
overpass not configured, falling back to public overpass api
transit stops query not configured, falling back to default
analysis.trip_model.conf.json not configured, falling back to sample, default configuration
expectations.conf.json not configured, falling back to sample, default configuration
ERROR:root:habitica not configured, game functions not supported
Traceback (most recent call last):
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/net/ext_service/habitica/proxy.py", line 22, in <module>
    key_file = open('conf/net/ext_service/habitica.json')
FileNotFoundError: [Errno 2] No such file or directory: 'conf/net/ext_service/habitica.json'
2025-03-28T08:27:11.836248-07:00**********UUID ddd3ec92-9dc6-4e39-bda7-4a0b454502e4: moving to long term**********
New entry count == 0 and skip_if_no_new_data = False, continuing
2025-03-28T08:27:11.846977-07:00**********UUID ddd3ec92-9dc6-4e39-bda7-4a0b454502e4: updating incoming user inputs**********
2025-03-28T08:27:11.870310-07:00**********UUID ddd3ec92-9dc6-4e39-bda7-4a0b454502e4: filter accuracy if needed**********
2025-03-28T08:27:11.874877-07:00**********UUID ddd3ec92-9dc6-4e39-bda7-4a0b454502e4: segmenting into trips**********
2025-03-28T08:27:12.235086-07:00**********UUID ddd3ec92-9dc6-4e39-bda7-4a0b454502e4: segmenting into sections**********
Sectioning failed for user ddd3ec92-9dc6-4e39-bda7-4a0b454502e4
Traceback (most recent call last):
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/analysis/intake/segmentation/section_segmentation.py", line 68, in segment_current_sections
    entries_to_insert += segment_trip_into_sections(
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/analysis/intake/segmentation/section_segmentation.py", line 137, in segment_trip_into_sections
    trip_start_loc = ecwl.Location(trip_filtered_loc_df.iloc[0])
  File "/Users/kshankar/miniconda-23.5.2/envs/emission/lib/python3.9/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/Users/kshankar/miniconda-23.5.2/envs/emission/lib/python3.9/site-packages/pandas/core/indexing.py", line 1625, in _getitem_axis
    self._validate_integer(key, axis)
  File "/Users/kshankar/miniconda-23.5.2/envs/emission/lib/python3.9/site-packages/pandas/core/indexing.py", line 1557, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
2025-03-28T08:27:13.074640-07:00**********UUID ddd3ec92-9dc6-4e39-bda7-4a0b454502e4: smoothing sections**********
2025-03-28T08:27:13.083266-07:00**********UUID ddd3ec92-9dc6-4e39-bda7-4a0b454502e4: cleaning and resampling timeline**********
2025-03-28T08:27:14.160781-07:00**********UUID ddd3ec92-9dc6-4e39-bda7-4a0b454502e4: inferring labels**********
2025-03-28T08:27:14.168122-07:00**********UUID ddd3ec92-9dc6-4e39-bda7-4a0b454502e4: populating expectations**********
2025-03-28T08:27:14.176301-07:00**********UUID ddd3ec92-9dc6-4e39-bda7-4a0b454502e4: creating confirmed objects **********
2025-03-28T08:27:14.184856-07:00**********UUID ddd3ec92-9dc6-4e39-bda7-4a0b454502e4: creating composite objects **********
2025-03-28T08:27:14.258943-07:00**********UUID ddd3ec92-9dc6-4e39-bda7-4a0b454502e4: storing user stats **********
```