Fix the pandas unit test
We need to create a cleaned trip object and pass it in properly.
Otherwise we get the error:

```
Traceback (most recent call last):
  File "/home/runner/work/e-mission-server/e-mission-server/emission/tests/netTests/TestMetricsConfirmedTripsPandas.py", line 97, in testGetSpeedsForTrip
    speeds_list = trip_df.apply(earms._get_speeds_for_trip, axis=1)
  File "/home/runner/miniconda-4.8.3/envs/emissiontest/lib/python3.7/site-packages/pandas/core/frame.py", line 7541, in apply
    return op.get_result()
  File "/home/runner/miniconda-4.8.3/envs/emissiontest/lib/python3.7/site-packages/pandas/core/apply.py", line 180, in get_result
    return self.apply_standard()
  File "/home/runner/miniconda-4.8.3/envs/emissiontest/lib/python3.7/site-packages/pandas/core/apply.py", line 255, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/runner/miniconda-4.8.3/envs/emissiontest/lib/python3.7/site-packages/pandas/core/apply.py", line 284, in apply_series_generator
    results[i] = self.f(v)
  File "/home/runner/work/e-mission-server/e-mission-server/emission/analysis/result/metrics/simple_metrics.py", line 65, in _get_speeds_for_trip
    section_list = esdt.get_cleaned_sections_for_trip(trip_df_row.user_id, trip_df_row.cleaned_trip)
  File "/home/runner/miniconda-4.8.3/envs/emissiontest/lib/python3.7/site-packages/pandas/core/generic.py", line 5130, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'cleaned_trip'
```

+ comment out extraneous logging statements