Fix the `elif` check before any `if`
Fix regression caused by 63f3bb3cea0dd72f9c79a4b2abcad7938f70a796

Error

```
======================================================================
ERROR: netTests.TestWebserver (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: netTests.TestWebserver
Traceback (most recent call last):
  File "/home/runner/miniconda-23.1.0/envs/emissiontest/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/runner/miniconda-23.1.0/envs/emissiontest/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/e-mission-server/e-mission-server/emission/tests/netTests/TestWebserver.py", line 21, in <module>
    import emission.net.api.cfc_webapp as enacw
  File "/home/runner/work/e-mission-server/e-mission-server/emission/net/api/cfc_webapp.py", line 502
    elif dynamic_config["intro"]["program_or_study"] == "program":
    ^
SyntaxError: invalid syntax
```