:white_check_mark: Really ensure that configs are stashed properly
Before this, we attempted to stash the config before changing it
by using code similar to `config_stash = <module>.config`

Alas, due to the lack of a `copy.copy` around it, the stashed value was just a
reference to the original value, and any further modifications to
`<module.config` are also reflected in the stash.

So restoring at the end using `<module>.config = config_stash` doesn't actually
restore it.

This is not visible while running the tests individually since we don't attempt
to use the "restored" value after it is restored.

However, while running multiple test in the same process, the overriden config
is retained and causes other tests to fail.

Concretely:
- the `preprocess_trip` trip option from `TestExpectationPipeline.py` was not
  reverted, and ended up causing an unrelated test (TestPipelineReset) to fail
    with the following error

```
======================================================================
ERROR: testResetToFuture (pipelineTests.TestPipelineReset.TestPipelineReset)
- Load data for both days
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/e-mission-server/e-mission-server/emission/tests/pipelineTests/TestPipelineReset.py", line 412, in testResetToFuture
    etc.runIntakePipeline(self.testUUID)
  File "/home/runner/work/e-mission-server/e-mission-server/emission/tests/common.py", line 196, in runIntakePipeline
    eaue.populate_expectations(uuid)
  File "/home/runner/work/e-mission-server/e-mission-server/emission/analysis/userinput/expectations.py", line 23, in populate_expectations
    expected_trip = _process_and_save_trip(user_id, inferred_trip, ts)
  File "/home/runner/work/e-mission-server/e-mission-server/emission/analysis/userinput/expectations.py", line 38, in _process_and_save_trip
    if _test_options["preprocess_trip"] is not None: _test_options["preprocess_trip"](expected_trip)
  File "/home/runner/work/e-mission-server/e-mission-server/emission/tests/pipelineTests/TestExpectationPipeline.py", line 61, in <lambda>
    eaue._test_options["preprocess_trip"] = lambda trip: self.preprocess(trip)
  File "/home/runner/work/e-mission-server/e-mission-server/emission/tests/pipelineTests/TestExpectationPipeline.py", line 67, in preprocess
    trip["data"]["end_ts"] = self.contrived_dates[self.fingerprint(trip)].float_timestamp
KeyError: 566
```

Change: Add `copy.copy` to all config stashes

Testing done:

```
PYTHONPATH=. python -m unittest discover -s emission/tests/pipelineTests/ -p Test*
```

results in

```
----------------------------------------------------------------------
Ran 35 tests in 294.002s

OK
```