✅ Really fix the `testJun20*load` ground truth
Before this, we were only checking for the start and end times, so we didn't need alt entries.
But we now check for the locations as well
https://github.com/e-mission/e-mission-server/pull/922/commits/ce6d472cdf74ce4c59288e5a8d042f56a9e27cee

And those apparently differ

Fixing them and creating `alt` checks for all ground truth

```
======================================================================
FAIL: testCompositeTripIncrementalLastPlaceMatches (analysisTests.intakeTests.TestPipelineRealData.TestPipelineRealData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/e-mission-server/e-mission-server/emission/tests/analysisTests/intakeTests/TestPipelineRealData.py", line 885, in testCompositeTripIncrementalLastPlaceMatches
    self.compare_composite_objects(composite_trips[i], expected_trips[i])
  File "/home/runner/work/e-mission-server/e-mission-server/emission/tests/analysisTests/intakeTests/TestPipelineRealData.py", line 720, in compare_composite_objects
    self.assertEqual([l['data']['ts'] for l in  ct['data']['locations']],
AssertionError: Lists differ: [1681[348 chars]1681437403.402, 1681437433.402, 1681437463.402, 1681437479.975] != [1681[348 chars]1681437403.402, 1681437419.975, 1681437450.978, 1681437479.975]

First differing element 23:
1681437433.402
1681437419.975
```