While appending entries, do so after the last _index_ and not the _length_
While appending entries, we were setting the index based on len(loc_df).
The problem is that if we had deleted entries earlier, then indexes don't
match the length.

And in pandas, if you set an index that already exists, you get the column
_names_ appended, not the values.

```
>>> loc_df = pd.DataFrame.from_csv("55da26137d65cb39ee98558d.csv")

>>> len(loc_df)
3

>>> loc_df[["fmt_time", "ts", "latitude", "longitude"]]
    fmt_time    ts  latitude    longitude
1   2015-08-23T12:30:43.906000-07:00    1440358243.910000   37.392953   -122.085000
2   2015-08-23T12:31:12.940000-07:00    1440358272.940000   37.392953   -122.085000
3   2015-08-23T12:31:43.969000-07:00    1440358303.970000   37.392986   -122.084981

>>> loc_df.loc[3] = {u'loc': {u'type': u'Point', u'coordinates': [-122.0862751, 37.3909233]}, u'local_dt_timezone': u'America/Los_Angeles', u'local_dt_hour': 12, u'fmt_time': u'2015-08-23T12:34:14.493000-07:00', u'local_dt_minute': 34, u'altitude': 0, u'local_dt_year': 2015, u'local_dt_second': 14, u'ts': 1440358454.493, u'longitude': -122.0862751, u'local_dt_month': 8, u'filter': u'time', u'local_dt_weekday': 6, 'metadata_write_ts': 1440358455.195, u'latitude': 37.3909233, 'user_id': UUID('0763de67-f61e-3f5d-90e7-518e69793954'), u'local_dt_day': 23, u'heading': 0, u'sensed_speed': 0, u'accuracy': 37.5}

>>> loc_df[["fmt_time", "ts", "latitude", "longitude"]]
    fmt_time    ts  latitude    longitude
1   2015-08-23T12:30:43.906000-07:00    1440358243.910000   37.392953   -122.085000
2   2015-08-23T12:31:12.940000-07:00    1440358272.940000   37.392953   -122.085000
3   metadata_write_ts   sensed_speed    local_dt_timezone   accuracy
```

Because of this, we ended up with the error

```
Found error Could not match input to any of [u'YYYY-MM-DD', u'YYYY/MM/DD', u'YYYY.MM.DD', u'YYYY-MM', u'YYYY/MM', u'YYYY.MM', u'YYYY', u'YYYY', u'YYYY'] on 'sensed_speed' while processing trip Entry({...})
ParserError: Could not match input to any of [u'YYYY-MM-DD', u'YYYY/MM/DD', u'YYYY.MM.DD', u'YYYY-MM', u'YYYY/MM', u'YYYY.MM', u'YYYY', u'YYYY', u'YYYY'] on 'sensed_speed'
```

The fix is to determine the index based on the prior index, not the length. We reset the index anyway after this, so it doesn't matter too much.

Also add some additional logging to help debug what's going on.