🐛 Handle `last_processed_ts` existing but None
While checking to see if the pipeline is up to date, we look at the
`last_processed_ts` of the trip segmentation stage. We retrieve it using `get`
to handle the case where it doesn't exist. However, if it exists but is None,
then wrapping it in an arrow object fails.

```
Found error Cannot parse argument of type None. while processing pipeline for user <UUID>, skipping
Traceback (most recent call last):
File "/usr/src/app/emission/pipeline/intake_stage.py", line 78, in run_intake_pipeline
run_intake_pipeline_for_user(uuid)
File "/usr/src/app/emission/pipeline/intake_stage.py", line 108, in run_intake_pipeline_for_user
last_trip_segment_processed_ts = arrow.get(trip_segment_stage.get("last_processed_ts", 0))
File "/root/miniconda-25.1.1/envs/emission/lib/python3.9/site-packages/arrow/api.py", line 91, in get
return _factory.get(*args, **kwargs)
File "/root/miniconda-25.1.1/envs/emission/lib/python3.9/site-packages/arrow/factory.py", line 227, in get
raise TypeError("Cannot parse argument of type None.")
TypeError: Cannot parse argument of type None.
```

This is the real fix for https://github.com/e-mission/e-mission-docs/issues/1131
The issue was incorrectly diagnosed initially, the challenge is not that the
pipeline range is None but that the `last_processed_ts` is None.

Testing done:
- Pulled data for `smart-commute`
- Reproduced the error

```
Found error Cannot parse argument of type None. while processing pipeline for user redacted-user-1, skipping
Traceback (most recent call last):
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/pipeline/intake_stage.py", line 78, in run_intake_pipeline
    run_intake_pipeline_for_user(uuid)
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/pipeline/intake_stage.py", line 108, in run_intake_pipeline_for_user
    last_trip_segment_processed_ts = arrow.get(trip_segment_stage.get("last_processed_ts", 0))
  File "/Users/kshankar/miniconda-25.1.1/envs/emission/lib/python3.9/site-packages/arrow/api.py", line 91, in get
    return _factory.get(*args, **kwargs)
  File "/Users/kshankar/miniconda-25.1.1/envs/emission/lib/python3.9/site-packages/arrow/factory.py", line 227, in get
    raise TypeError("Cannot parse argument of type None.")
TypeError: Cannot parse argument of type None.
```

- After this change, the pipeline launches successfully

```
2025-07-07T14:27:52.426162-07:00**********UUID redacted-user-1: moving to long term**********
Creating usercache_compound_hack index in the background
2025-07-07T14:28:09.344998-07:00**********UUID redacted-user-1: updating incoming user inputs**********
2025-07-07T14:28:14.427709-07:00**********UUID redacted-user-1: filter accuracy if needed**********
2025-07-07T14:28:14.444610-07:00**********UUID redacted-user-1: segmenting into trips**********
```