Remove manual install test on OSX
We tried to add a test using an OSX manual install, but it failed with the error
So we can only continue to test on linux for now

```
Run supercharge/mongodb-github-action@1.3.0
  with:
    mongodb-version: 4.4.0
Error: Container action is only supported on Linux
```