♻️  Refactor and simplify the conda install script
- Support specifying an install prefix
- Since we now have three input variables, restructure the input checks and add
  new ones (suggested by copilot)

I also tried to remove the mamba-solver installation (`conda install -n base
conda-libmamba-solver`) since it is included by default

https://conda.github.io/conda-libmamba-solver/user-guide/

> If you have a recent conda (23.10 or later), you don’t have to do anything. conda-libmamba-solver is already preconfigured as default. For older versions conda, we simply recommend updating conda to a more recent version:

However, removing it cause the tests to fail with

```
======================================================================
ERROR: analysisTests.modeinferTests.TestPipeline (unittest.loader._FailedTest.analysisTests.modeinferTests.TestPipeline)
----------------------------------------------------------------------
ImportError: Failed to import test module: analysisTests.modeinferTests.TestPipeline
Traceback (most recent call last):
  File "/home/runner/miniconda-25.1.1/envs/emissiontest/lib/python3.11/unittest/loader.py", line 419, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda-25.1.1/envs/emissiontest/lib/python3.11/unittest/loader.py", line 362, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/e-mission-server/e-mission-server/emission/tests/analysisTests/modeinferTests/TestPipeline.py", line 22, in <module>
    import emission.core.wrapper.localdate as ecwl
  File "/home/runner/work/e-mission-server/e-mission-server/emission/core/wrapper/localdate.py", line 10, in <module>
    import emission.core.wrapper.wrapperbase as ecwb
  File "/home/runner/work/e-mission-server/e-mission-server/emission/core/wrapper/wrapperbase.py", line 9, in <module>
    import attrdict as ad
  File "/home/runner/miniconda-25.1.1/envs/emissiontest/lib/python3.11/site-packages/attrdict/__init__.py", line 5, in <module>
    from attrdict.mapping import AttrMap
  File "/home/runner/miniconda-25.1.1/envs/emissiontest/lib/python3.11/site-packages/attrdict/mapping.py", line 4, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/home/runner/miniconda-25.1.1/envs/emissiontest/lib/python3.11/collections/__init__.py)
```

It looks like including the libmambasolver installs python 3.9 instead, which
works. We will need to upgrade to a later version of python, and handle the
mapping issue, but punting on it for now...

Testing done:
- Used to install the new miniconda for c4333fdad09c1ba57ab0d541f8bcd36d28ecb9f0