♻️  Move the api configuration into the backwards compat as well
Consistent with
https://github.com/e-mission/e-mission-server/pull/961#issuecomment-2282206511
and 7f1be920098f644d863536a5e810343f2634fc28 (which was the original example
for the database)

Testing done:

1. Started the webapp with no overridden config

```
Config file not found, returning a copy of the environment variables instead...
Finished configuring logging for <RootLogger root (WARNING)>
Using auth method skip
Replaced json_dumps in plugin with the one from bson
Changing bt.json_loads from <function <lambda> at 0x10b2b08b0> to <function <lambda> at 0x10bd6a940>
Running with HTTPS turned OFF - use a reverse proxy on production
Bottle v0.13-dev server starting up (using CherootServer())...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.
```

2. Started the webapp with an invalid config override

```
ERROR:root:Expecting ',' delimiter: line 12 column 5 (char 464)
Traceback (most recent call last):
  File "/Users/kshankar/Desktop/data/e-mission/gis_branch_tests/emission/core/backwards_compat_config.py", line 28, in get_config
    loaded_val = pd.json_normalize(json.load(config_file)).iloc[0]
...
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 12 column 5 (char 464)
Config file not found, returning a copy of the environment variables instead...
```

3. Started the webapp with a valid config override

```
Finished configuring logging for <RootLogger root (WARNING)>
Using auth method token_list
Replaced json_dumps in plugin with the one from bson
Changing bt.json_loads from <function <lambda> at 0x10fd2a8b0> to <function <lambda> at 0x1107e5940>
Running with HTTPS turned OFF - use a reverse proxy on production
Bottle v0.13-dev server starting up (using CherootServer())...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.
```