Add support to compare algorithm changes (#762)
* Add support to compare algorithm changes

This is primarily focused at updating the ground truth for unit tests in
response to algorithm changes. Since the algorithm changes will change the
output in subtle ways, we need to compare the old and new outputs and manually
confirm that the newer is better. We can't use automated techniques since we
don't have "ground truth", only a reference output.

The new `bin/compare_algo_changes.py` script facilitates this by running the
test cases outside the test framework and passing in additional flags. The
additional flags cause a user to be registered, so that we can access the
visualization in the phone, and download the ground truth so we can easily
update it after checking.

More details at https://github.com/e-mission/e-mission-docs/tree/master/docs/dev/back/algo_changes_outcome.md

Testing done:

```
./e-mission-py.bash bin/compare_algo_changes.py master emission.tests.analysisTests.intakeTests.TestPipelineRealData TestPipelineRealData --test testGabeShortTrips
```
generated `/tmp/gabe_2016-06-15.ground_truth`

Connecting from phones showed the diary

-------

```
./e-mission-py.bash bin/compare_algo_changes.py master emission.tests.analysisTests.intakeTests.TestPipelineRealData TestPipelineRealData --test testGabeShortTrips
```
resulted in

```
DEBUG:root:Clearing related databases for 19a82bd8-aef3-4f9c-a158-bf3826296196
INFO:root:Timeseries delete result {'n': 1419, 'ok': 1.0}
INFO:root:Analysis delete result {'n': 249, 'ok': 1.0}
INFO:root:Usercache delete result {'n': 0, 'ok': 1.0}
```

Connecting from phones did not show the diary

-------

Manually inserting an error into the test caused the error to be printed out

* Remove unnecessary print statements

They make this be unnecessarily verbose AND cause failures when the field does not exist.

```
2020-08-15T06:30:24.1796113Z ======================================================================
2020-08-15T06:30:24.1796466Z ERROR: testGabeShortTrips (analysisTests.intakeTests.TestPipelineRealData.TestPipelineRealData)
2020-08-15T06:30:24.1797775Z ----------------------------------------------------------------------
2020-08-15T06:30:24.1798016Z Traceback (most recent call last):
2020-08-15T06:30:24.1798811Z   File "/home/runner/work/e-mission-server/e-mission-server/emission/tests/analysisTests/intakeTests/TestPipelineRealData.py", line 321, in testGabeShortTrips
2020-08-15T06:30:24.1799112Z     print("self.evaluation = %s" % self.evaluation)
2020-08-15T06:30:24.1799715Z AttributeError: 'TestPipelineRealData' object has no attribute 'evaluation'
2020-08-15T06:30:24.1799879Z
```