Forcing an order on the keys returned from `getKeyListForType`
Before this change, we were returning the values in the database order

```
    def getKeyListForType(self, message_type):
        return self.db.find({"user_id": self.user_id, "metadata.type": message_type}).distinct("metadata.key")
```

The database order changed between 3.4.0 and 4.4.0, leading to a regression when we tested with
c71712fcee43940543bfe705f93c5e1e868864db

```
======================================================================
FAIL: testDeleteObsoleteEntries (__main__.TestBuiltinUserCacheHandlerOutput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "emission/tests/netTests/TestBuiltinUserCacheHandlerOutput.py", line 121, in testDeleteObsoleteEntries
    self.assertEqual(uc.getDocumentKeyList(), ["2015-12-30", "2015-12-29"])
AssertionError: Lists differ: ['2015-12-29', '2015-12-30'] != ['2015-12-30', '2015-12-29']

First differing element 0:
'2015-12-29'
'2015-12-30'

- ['2015-12-29', '2015-12-30']
+ ['2015-12-30', '2015-12-29']
```

We now force an order and update the checks to verify that order