Check in some more logs for intermittent test failure
This test fails in jenkins with the error

```
======================================================================
FAIL: testNoData (storageTests.TestTourModelQueries.TestTourModelQueries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/e-mission-server-prb/emission/tests/storageTests/TestTourModelQueries.py", line 37, in testNoData
    self.assertTrue(len(tm["common_places"]) == 0)
AssertionError: False is not true

----------------------------------------------------------------------
```

But it does not fail locally. We need to see what's going on in more detail,
so we add some logging to help us debug.