Remove unnecessary print statements
They make this be unnecessarily verbose AND cause failures when the field does not exist.

```
2020-08-15T06:30:24.1796113Z ======================================================================
2020-08-15T06:30:24.1796466Z ERROR: testGabeShortTrips (analysisTests.intakeTests.TestPipelineRealData.TestPipelineRealData)
2020-08-15T06:30:24.1797775Z ----------------------------------------------------------------------
2020-08-15T06:30:24.1798016Z Traceback (most recent call last):
2020-08-15T06:30:24.1798811Z   File "/home/runner/work/e-mission-server/e-mission-server/emission/tests/analysisTests/intakeTests/TestPipelineRealData.py", line 321, in testGabeShortTrips
2020-08-15T06:30:24.1799112Z     print("self.evaluation = %s" % self.evaluation)
2020-08-15T06:30:24.1799715Z AttributeError: 'TestPipelineRealData' object has no attribute 'evaluation'
2020-08-15T06:30:24.1799879Z
```