♻️  Make the dynamic config available more broadly
Before this, the dynamic config was read in `resolve_auth` and only used to
choose the authentication method if it was dynamic. However, as we make more
parts of the server also controlled via the dynamic config, we will want to
make the dynamic config more broadly available.

This change pulls out the dynamic config into a separate function, invokes it
before resolving the auth, and passes it in the `resolve_auth` function.

A potential cleanup would be to pull it up even further (into
`emission.core.dynamic_config`, similar to
`emission/core/backwards_compat_config.py`) so that it could be used more
easily in other modules as well.

Testing done:

auth_mode = skip

```
2025-02-02 12:43:15,973:DEBUG:8313653312:Using auth method skip
2025-02-02 12:45:30,066:DEBUG:6329921536:START POST /profile/create
2025-02-02 12:45:30,068:DEBUG:6329921536:Called createUserProfile
2025-02-02 12:45:30,074:DEBUG:6329921536:methodName = skip, returning <class 'emission.net.aut
h.skip.SkipMethod'>
2025-02-02 12:45:30,075:DEBUG:6329921536:Using the skip method to verify id token nrelop_dev-e
mulator-study_default_123 of length 37
2025-02-02 12:45:30,075:DEBUG:6329921536:userEmail = nrelop_dev-emulator-study_default_123
...
2025-02-02 12:45:30,103:DEBUG:6329921536:END POST /profile/create  0.0375370979309082
```

auth_mode = dynamic, but token not in token list

```
ValueError: Invalid token nrelop_dev-emulator-study_default_123, not found in list of length 0

2025-02-02 12:49:37,234:DEBUG:8313653312:auth_method is dynamic, using dynamic config to find
the actual auth method
2025-02-02 12:49:37,234:DEBUG:8313653312:is a program set auth_method to token_list
2025-02-02 12:49:37,235:DEBUG:8313653312:Using auth method token_list
2025-02-02 12:50:07,735:DEBUG:6353514496:START POST /profile/create
2025-02-02 12:50:07,737:DEBUG:6353514496:Called createUserProfile
et.auth.token_list.TokenListMethod'>
2025-02-02 12:50:07,744:DEBUG:6370340864:methodName = token_list, returning <class 'emission.n
et.auth.token_list.TokenListMethod'>
2025-02-02 12:50:07,746:DEBUG:6353514496:Using the TokenListMethod to verify id token nrelop_d
ev-emulator-study_default_123 of length 37 against list []...
2025-02-02 12:50:07,749:DEBUG:6353514496:END POST /profile/create  0.015098094940185547
```

auth_mode = dynamic, token in token list

```
./e-mission-py.bash bin/auth/insert_tokens.py --single nrelop_dev-emulator-study_default_123
Config file not found, returning a copy of the environment variables instead...
Retrieved config: {'DB_HOST': None, 'DB_RESULT_LIMIT': None}
URL not formatted, defaulting to "Stage_database"
Connecting to database URL localhost

2025-02-02 12:53:31,260:DEBUG:8313653312:attempting to resolve auth_method
2025-02-02 12:53:31,261:DEBUG:8313653312:STUDY_CONFIG is stage-program
2025-02-02 12:53:31,261:DEBUG:8313653312:About to download config from https://raw.githubuserc
ontent.com/e-mission/nrel-openpath-deploy-configs/main/configs/stage-program.nrel-op.json
2025-02-02 12:53:31,368:DEBUG:8313653312:Successfully downloaded config with version 1 for Sta
ging environment for testing programs only and data collection URL https://openpath-stage.nrel
.gov/api/
2025-02-02 12:53:31,369:DEBUG:8313653312:auth_method is dynamic, using dynamic config to find the actual auth method
2025-02-02 12:53:31,369:DEBUG:8313653312:is a program set auth_method to token_list
2025-02-02 12:53:31,369:DEBUG:8313653312:Using auth method token_list
2025-02-02 12:54:15,996:DEBUG:13186920448:START POST /profile/create
2025-02-02 12:54:15,997:DEBUG:13186920448:Called createUserProfile
2025-02-02 12:54:16,001:DEBUG:13186920448:methodName = token_list, returning <class 'emission.net.auth.token_list.TokenListMethod'>
2025-02-02 12:54:16,011:DEBUG:13203746816:Using the TokenListMethod to verify id token nrelop_dev-emulator-study_default_123 of length 37 against list ['nrelop_dev-emulator-study_default_123']...
2025-02-02 12:54:16,011:DEBUG:13203746816:Found match for token nrelop_dev-emulator-study_default_123 of length 37
2025-02-02 12:54:16,014:DEBUG:13203746816:retUUID = eb4a7aae-f2d4-4480-ba85-c568a45591b5
2025-02-02 12:54:16,016:DEBUG:13186920448:Looked up user = <emission.core.wrapper.user.User object at 0x3105a3820>
2025-02-02 12:54:16,016:DEBUG:13186920448:Returning result {'uuid': 'eb4a7aae-f2d4-4480-ba85-c568a45591b5'}
2025-02-02 12:54:16,017:DEBUG:13186920448:END POST /profile/create  0.020717620849609375
```