Fix all inputs to `nonzero`
Due to changes in the way that pandas interacts with numpy, `numpy.nonzero`
does not work properly with pandas series (see example below).

```
$ ./e-mission-py.bash
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:37:09)
[Clang 10.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> import numpy as np
>>> s = pd.Series([True, False, True, False, False, True])
>>> np.nonzero(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in nonzero
  File "/Users/kshankar/miniconda-4.8.3/envs/emission/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1908, in nonzero
    return _wrapfunc(a, 'nonzero')
  File "/Users/kshankar/miniconda-4.8.3/envs/emission/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 55, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/kshankar/miniconda-4.8.3/envs/emission/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 48, in _wrapit
    result = wrap(result)
  File "/Users/kshankar/miniconda-4.8.3/envs/emission/lib/python3.7/site-packages/pandas/core/generic.py", line 1787, in __array_wrap__
    return self._constructor(result, **d).__finalize__(
  File "/Users/kshankar/miniconda-4.8.3/envs/emission/lib/python3.7/site-packages/pandas/core/series.py", line 314, in __init__
    f"Length of passed values is {len(data)}, "
ValueError: Length of passed values is 1, index implies 6.
>>> np.nonzero(s.to_numpy())
(array([0, 2, 5]),)
```

We fix this by changing

`np.nonzero(s)` ➡️  `np.nonzero(s.to_numpy())` iff `s` is a pandas series

This change was only in one file
- `emission//analysis/intake/segmentation/section_segmentation_methods/smoothed_high_confidence_motion.py`: fixed

The others were already numpy arrays and did not need conversion

- `emission//analysis/classification/inference/mode/seed/pipeline.py`: the `featureMatrix` is an numpy array
- `emission//analysis/classification/inference/Classifier.ipynb`: Ditto
- `emission//analysis/modelling/tour_model/prior_unused/exploratory_scripts/plot_error_types.py`: the array is already a numpy array
- `emission//analysis/intake/cleaning/cleaning_methods/jump_smoothing.py`: `inlier_mask_` seems to be a normal array. Tested in `emission//tests/analysisTests/intakeTests/TestLocationSmoothing.py`
- `emission//analysis/intake/cleaning/cleaning_methods/jump_smoothing.py`: `inlier_mask_` seems to be a normal array. Tested in `emission//tests/analysisTests/intakeTests/TestLocationSmoothing.py`
- `emission//incomplete_tests/TestGpsSmoothing.py`: ditto