Ensure that the composite trip metadata reflects the time that it was created
Bonus fix: use the existing `ecwe.Entry.create_entry` to fill in the new entry
instead of manually recreating

Also enhance the tests to check for the metadata

Bonus fix: Remove incorrect check for `testShankariUntrackedTimeJul20`
The composite trip code only checks for `cleaned_untracked`, so `raw_untracked`
segments will not show up as composite trips, so we do not expect to find one
`raw_untracked` time entry

Testing done:

Added intentional error to one of the tests (write_ts less than start), it failed

======================================================================
FAIL: testShankariNotUntrackedTimeJan15 (__main__.TestPipelineRealData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "emission/tests/analysisTests/intakeTests/TestPipelineRealData.py", line 756, in testShankariNotUntrackedTimeJan15
    self.assertLess(ct["metadata"]["write_ts"], start_run)
AssertionError: 1680716084.451522 not less than 1680716064.349642

----------------------------------------------------------------------

Only one pipeline test fails (fixing in the next commit)

```
./e-mission-py.bash emission/tests/analysisTests/intakeTests/TestPipelineRealData.py

======================================================================
FAIL: testJackUntrackedTimeMar12 (__main__.TestPipelineRealData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "emission/tests/analysisTests/intakeTests/TestPipelineRealData.py", line 723, in testJackUntrackedTimeMar12
    self.compare_composite_objects(composite_trips[i], expected_trips[i])
  File "emission/tests/analysisTests/intakeTests/TestPipelineRealData.py", line 703, in compare_composite_objects
    self.assertEqual(ct['data']['start_ts'], et['data']['start_ts'])
AssertionError: 1678642210.9015162 != 1678651111.264

----------------------------------------------------------------------
Ran 1 test in 21.336s
```