Returning a 403 error properly when we generate a ValueError on auth
Before the fix:

```
Traceback (most recent call last):
  File "emission/net/api/cfc_webapp.py", line 466, in createUserProfile
    userEmail = enaa._getEmail(request, auth_method)
  File "/usr/src/app/e-mission-server/emission/net/auth/auth.py", line 77, in _getEmail
    userEmail = AuthMethodFactory.getAuthMethod(authMethod).verifyUserToken(userToken)
  File "/usr/src/app/e-mission-server/emission/net/auth/token_list.py", line 40, in verifyUserToken
    (token, len(self.token_list)))
ValueError: Invalid token [redacted], not found in list of length 100
Traceback (most recent call last):
  File "emission/net/api/cfc_webapp.py", line 466, in createUserProfile
    userEmail = enaa._getEmail(request, auth_method)
  File "/usr/src/app/e-mission-server/emission/net/auth/auth.py", line 77, in _getEmail
    userEmail = AuthMethodFactory.getAuthMethod(authMethod).verifyUserToken(userToken)
  File "/usr/src/app/e-mission-server/emission/net/auth/token_list.py", line 40, in verifyUserToken
    (token, len(self.token_list)))
ValueError: Invalid token [redacted], not found in list of length 100

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/e-mission-server/emission/net/api/bottle.py", line 997, in _handle
    out = route.call(**args)
  File "/usr/src/app/e-mission-server/emission/net/api/bottle.py", line 1998, in wrapper
    rv = callback(*a, **ka)
  File "emission/net/api/cfc_webapp.py", line 478, in createUserProfile
    abort(403, e.message)
AttributeError: 'ValueError' object has no attribute 'message'
```

The error was caused because the argument to `ValueError` is not stored as `message`

```
>>> try:
...     raise ValueError("this is a value error")
... except ValueError as e:
...     print(e.message)
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ValueError: this is a value error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
AttributeError: 'ValueError' object has no attribute 'message'
```

but as `args

```
>>> try:
...     raise ValueError("this is a value error")
... except ValueError as e:
...     print(str(e.args))
...
('this is a value error',)
```

After the fix

```
START 2021-06-07 16:26:33.639987 POST /profile/create
Traceback (most recent call last):
  File "emission/net/api/cfc_webapp.py", line 312, in createUserProfile
    userEmail = enaa._getEmail(request, auth_method)
  File "/Users/kshankar/e-mission/e-mission-server/emission/net/auth/auth.py", line 77, in _getEmail
    userEmail = AuthMethodFactory.getAuthMethod(authMethod).verifyUserToken(userToken)
  File "/Users/kshankar/e-mission/e-mission-server/emission/net/auth/token_list.py", line 40, in verifyUserToken
    (token, len(self.token_list)))
ValueError: Invalid token testme, not found in list of length 250
END 2021-06-07 16:26:33.644540 POST /profile/create  0.004488229751586914
```