Handle error model with picking the correct timezone
It turns out that the jumps are so weird that we can sometimes have different
timezones and have them overlap in a totally weird way. We do some sanity
checking around this...

The original error was:

2016-04-24 20:59:27,133:DEBUG:tz_ranges = [{'timezone': u'America/Los_Angeles', 'end_ts': 1459464057.
537, 'start_ts': 1459464031.062}, {'timezone': u'America/Phoenix', 'end_ts': 1459464057.5369999, 'sta
rt_ts': 1459464057.537}]
2016-04-24 20:59:27,138:DEBUG:tz_ranges_df =          end_ts      start_ts             timezone
0  1.459464e+09  1.459464e+09  America/Los_Angeles
1  1.459464e+09  1.459464e+09      America/Phoenix

Traceback (most recent call last):
  File "/Users/shankari/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resamp
le.py", line 83, in save_cleaned_segments_for_timeline
    filtered_trip = get_filtered_trip(ts, trip)
  File "/Users/shankari/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resamp
le.py", line 131, in get_filtered_trip
    section_map[section.get_id()] = get_filtered_section(filtered_trip_entry, section)
  File "/Users/shankari/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resamp
le.py", line 198, in get_filtered_section
    with_speeds_df = get_filtered_points(section, filtered_section_data)
  File "/Users/shankari/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resamp
le.py", line 266, in get_filtered_points
    resampled_loc_df = resample(filtered_loc_list, interval=30)
  File "/Users/shankari/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resamp
le.py", line 331, in resample
    tz_new = [_get_timezone(ts, tz_ranges_df) for ts in ts_new]
  File "/Users/shankari/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 345, in _get_timezone
    assert len(sel_entry) == 1, "len(sel_entry = %d" % len(sel_entry)
AssertionError: len(sel_entry = 2