Comment out calls to graph the similarity
Since:
1) They are not checked anyway since the test framework does not provide
facilities for checking against images
2) In spite of having that matplotlib includes essentially unchanged since
Naomi's original checkin, I still see

```
Traceback (most recent call last):
  File "<https://amplab.cs.berkeley.edu/jenkins/job/e-mission-server-prb/ws/emission/tests/analysisTests/TestSimilarity.py",> line 124, in testGraph
    sim.graph()
  File "emission/analysis/modelling/tour_model/similarity.py", line 159, in graph
    plt.bar(index+width, bars, color='k')
  File "/home/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2566, in bar
    ax = gca()
  File "/home/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 828, in gca
    ax =  gcf().gca(**kwargs)
  File "/home/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 462, in gcf
    return figure()
  File "/home/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 435, in figure
    **kwargs)
  File "/home/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 47, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/home/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 54, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/home/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 72, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/home/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 68, in __init__
    _create_qApp()
  File "/home/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 138, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
```