Fix regression introduced in 16441ed9e
In 16441ed9e, @corinne-hcr introduced an additional return value from `cluster`.
While she changed the call location in her notebook, unfortunately, she did not
change the call location in the cluster pipeline driver.

This lead to the error in
https://github.com/e-mission/e-mission-server/pull/815#issue-653177984

```
Traceback (most recent call last):
  File "emission/analysis/modelling/tour_model/cluster_pipeline.py", line 99, in <module>
    main(uuid=uuid)
  File "emission/analysis/modelling/tour_model/cluster_pipeline.py", line 88, in main
    n, labels, data = cluster(data, len(bins))
ValueError: too many values to unpack (expected 3)
```

Testing done:
After the fix, there is no error

```
2021-05-25 21:35:21,704:DEBUG:in representatives, endpoints have len = 4
2021-05-25 21:35:21,704:DEBUG:For cluster 1, centers are [  37.39335332 -122.08335353   37.38773225 -122.08463903]
2021-05-25 21:35:21,705:DEBUG:number of locations: 4
```