Remove terminado
Build failed with error

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda 4.4.0 np112py36_0 -> terminado 0.6 py36_0
  - terminado 0.8 py36_0
```

Terminado does not appear to be actually used directly, maybe it is a dependency from something else?
If so, it should be included when the package we really want is included.
Let's remove it from the enviroment.xml