:arrow_up: Support the full confirmed timeline and composite trips in the reset code
Reset changes to fully support
https://github.com/e-mission/e-mission-server/pull/895

- `place_queries.py`: support the `CONFIRMED_PLACE_KEY` as a trip key query
- `reset.py`:
    - find the reset timestamp based on the last confirmed place instead of the
      last cleaned place since the confirmed timeline is the final timeline
    - return the last cleaned place as the cleaned place of the last confirmed place
    - open the confirmed place at the end of the confirmed timeline in addition
      to cleaned and raw places for their respective timelines
    - indicate that the composite trip creation also has fuzz

```
def mark_composite_object_creation_done(user_id, last_processed_ts):
    if last_processed_ts is None:
        mark_stage_done(user_id, ps.PipelineStages.CREATE_COMPOSITE_OBJECTS, None)
    else:
        mark_stage_done(user_id, ps.PipelineStages.CREATE_COMPOSITE_OBJECTS,
                        last_processed_ts + END_FUZZ_AVOID_LTE)
```

This fixes
https://github.com/e-mission/e-mission-server/pull/911#issuecomment-1527175756

But results in a new error
https://github.com/e-mission/e-mission-server/pull/911#issuecomment-1528845386

```
======================================================================
FAIL: testResetToTsInMiddleOfTrip (__main__.TestPipelineReset)
- Load data for both days
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/tests/pipelineTests/TestPipelineReset.py", line 311, in testResetToTsInMiddleOfTrip
    self.compare_result(ad.AttrDict({'result': api_result}).result,
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/tests/pipelineTests/TestPipelineReset.py", line 102, in compare_result
    self.assertEqual(rs.properties.exit_fmt_time, es.properties.exit_fmt_time)
AssertionError: '2016-07-25T17:12:27.853000-07:00' != '2016-07-22T17:21:36-07:00'
- 2016-07-25T17:12:27.853000-07:00
?          ^     - ----- ^^^
+ 2016-07-22T17:21:36-07:00
?          ^    +   ^
----------------------------------------------------------------------
```