🛂 Support the new config for auto versus pre-generated tokens
If the `opcode` field is present in the config, use it to determine whether the
tokens should be auto-generated or pre-generated.

If it is not, fall back to the old study vs program check.
We should remove the backwards compat code after all old-style configs have been removed

Testing done:
- Added new test with new style config
- Added new test for old style config that returns token list
- All tests pass

```
$ ./e-mission-py.bash emission/tests/netTests/TestWebServer.py
storage not configured, falling back to sample, default configuration
URL not formatted, defaulting to "Stage_database"
Connecting to database URL localhost
analysis.debug.conf.json not configured, falling back to sample, default configuration
ERROR:root:habitica not configured, game functions not supported
Traceback (most recent call last):
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/net/ext_service/habitica/proxy.py", line 22, in <module>
    key_file = open('conf/net/ext_service/habitica.json')
FileNotFoundError: [Errno 2] No such file or directory: 'conf/net/ext_service/habitica.json'
Finished configuring logging for <RootLogger root (WARNING)>
Finished configuring logging for <RootLogger root (WARNING)>
.Finished configuring logging for <RootLogger root (WARNING)>
.Finished configuring logging for <RootLogger root (WARNING)>
.
----------------------------------------------------------------------
Ran 3 tests in 0.735s

OK
```