Fix regression in the input matching for new entries
Matching for new user inputs broke (regression due to
https://github.com/e-mission/e-mission-server/commit/a7ee02c6e689f00368f88a219fd8d21c2da896ec)

The main issue was that we were filling in the `trip_additions` with None but only checking for existence.
More details at:
https://github.com/e-mission/e-mission-docs/issues/840#issuecomment-1397309417

Fixing it in two different ways:
- Returning `[]` instead of None from `get_not_deleted_candidates` if there are no filtered candidates
  This will ensure that we don't have a None value
- check for both None and existence. This will ensure that even if we do have a None value, we can recover gracefully

Testing done:

Original failure:

```
2023-01-19T09:58:57.198828-08:00**********UUID e20f451e-c619-46c8-a189-54310231bce5: updating incoming user inputs**********
Error while matching incoming user inputs, timestamp is unchanged
Traceback (most recent call last):
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/analysis/userinput/matcher.py", line 19, in match_incoming_user_inputs
    last_user_input_done = match_incoming_inputs(user_id, time_query)
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/analysis/userinput/matcher.py", line 46, in match_incoming_inputs
    handle_multi_non_deleted_match(confirmed_trip, ui)
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/analysis/userinput/matcher.py", line 70, in handle_multi_non_deleted_match
    confirmed_trip["data"]["trip_addition"].append(ui)
AttributeError: 'NoneType' object has no attribute 'append'
```

New failure (updating incoming), no `match_id`

```
2023-01-19T09:59:26.680014-08:00**********UUID e20f451e-c619-46c8-a189-54310231bce5: updating incoming user inputs**********
Error while matching incoming user inputs, timestamp is unchanged
Traceback (most recent call last):
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/analysis/userinput/matcher.py", line 19, in match_incoming_user_inputs
    last_user_input_done = match_incoming_inputs(user_id, time_query)
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/analysis/userinput/matcher.py", line 46, in match_incoming_inputs
    handle_multi_non_deleted_match(confirmed_trip, ui)
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/analysis/userinput/matcher.py", line 72, in handle_multi_non_deleted_match
    after_del_list = [ta for ta in confirmed_trip["data"]["trip_addition"] if ta["match_id"] != ui["match_id"]]
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/analysis/userinput/matcher.py", line 72, in <listcomp>
    after_del_list = [ta for ta in confirmed_trip["data"]["trip_addition"] if ta["match_id"] != ui["match_id"]]
KeyError: 'match_id'
```

New failure (creating objects), no `match_id`

```
2023-01-19T14:47:59.883681-08:00**********UUID e20f451e-c619-46c8-a189-54310231bce5: creating confirmed objects **********
Error while creating confirmed objects, timestamp is unchanged
Traceback (most recent call last):
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/analysis/userinput/matcher.py", line 81, in create_confirmed_objects
    last_expected_trip_done = create_confirmed_trips(user_id, time_query)
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/analysis/userinput/matcher.py", line 110, in create_confirmed_trips
    esdt.get_additions_for_trip_object(ts, tct)
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/storage/decorations/trip_queries.py", line 191, in get_additions_for_trip_object
    return get_not_deleted_candidates(valid_user_input(ts, trip_obj), potential_candidates)
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/storage/decorations/trip_queries.py", line 168, in get_not_deleted_candidates
    not_deleted_active = [efpc for efpc in all_active_list if efpc["match_id"] not in all_deleted_id]
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/storage/decorations/trip_queries.py", line 168, in <listcomp>
    not_deleted_active = [efpc for efpc in all_active_list if efpc["match_id"] not in all_deleted_id]
KeyError: 'match_id'
```