Check for the index before checking sparsity + pull out into separate function
Without this change, got the error:
```
======================================================================
ERROR: testQuery (storageTests.TestAnalysisTimeseries.TestAnalysisTimeseriesQueries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/e-mission-server/e-mission-server/emission/tests/storageTests/TestAnalysisTimeseries.py", line 31, in setUp
    edb.get_analysis_timeseries_db().delete_many({'user_id': self.testUserId})
  File "/home/runner/work/e-mission-server/e-mission-server/emission/core/get_database.py", line 199, in get_analysis_timeseries_db
    _create_analysis_result_indices(AnalysisTimeSeries)
  File "/home/runner/work/e-mission-server/e-mission-server/emission/core/get_database.py", line 217, in _create_analysis_result_indices
    if "sparse" in tscoll.index_information()["data.start_loc_2dsphere"]:
KeyError: 'data.start_loc_2dsphere'
```

So we need to check for the existence of the index before we check whether it is sparse