Minor fixes to the ground truth to match the new start_ts algorithm
It turns out that the change to use the min of the duration/2 and 3 minutes
for the extrapolated start_ts also made minor changes to existing ground truth.

Checking in the new ground truth...

```
======================================================================
FAIL: testAirTripHawaiiEnd (analysisTests.intakeTests.TestPipelineRealData.TestPipelineRealData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<https://amplab.cs.berkeley.edu/jenkins/job/e-mission-server-prb/ws/emission/tests/analysisTests/intakeTests/TestPipelineRealData.py",> line 322, in testAirTripHawaiiEnd
    ad.AttrDict(ground_truth).data)
  File "<https://amplab.cs.berkeley.edu/jenkins/job/e-mission-server-prb/ws/emission/tests/analysisTests/intakeTests/TestPipelineRealData.py",> line 99, in compare_result
    self.assertEqual(rs.properties.exit_fmt_time, es.properties.exit_fmt_time)
AssertionError: u'2016-08-04T14:06:52.592000-10:00' != u'2016-08-04T14:07:05.184000-10:00'
- 2016-08-04T14:06:52.592000-10:00
?                ^  - ^^^
+ 2016-08-04T14:07:05.184000-10:00
?                ^ +  ^^^
```

```
======================================================================
FAIL: testSquishedMismatchForUntrackedTime (analysisTests.intakeTests.TestPipelineRealData.TestPipelineRealData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<https://amplab.cs.berkeley.edu/jenkins/job/e-mission-server-prb/ws/emission/tests/analysisTests/intakeTests/TestPipelineRealData.py",> line 435, in testSquishedMismatchForUntrackedTime
    ad.AttrDict(ground_truth).data)
  File "<https://amplab.cs.berkeley.edu/jenkins/job/e-mission-server-prb/ws/emission/tests/analysisTests/intakeTests/TestPipelineRealData.py",> line 99, in compare_result
    self.assertEqual(rs.properties.exit_fmt_time, es.properties.exit_fmt_time)
AssertionError: u'2015-07-22T09:25:15.494000-07:00' != u'2015-07-22T09:26:34.517000-07:00'
- 2015-07-22T09:25:15.494000-07:00
?                 - ^^^^^
+ 2015-07-22T09:26:34.517000-07:00
?                +++++  ^
```