Don't break the composite trip creation pipeline stage if there are no trips
This fixes https://github.com/e-mission/e-mission-docs/issues/872
Before this, if there were no trips, the `create_composite_objects` method would
early return, so would not mark the pipeline stage as done.

So the `curr_run_ts` would be non zero, breaking the step forever and never
allowing it to run.

Added the one line fix + a new test case which runs the pipeline with no data
end ensures that all states are valid at the end.

Testing done:

Before this change:

```
======================================================================
FAIL: testNoData (__main__.TestPipelineRealData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "emission/tests/analysisTests/intakeTests/TestPipelineCornerCases.py", line 50, in testNoData
    self.assertIsNone(ps['curr_run_ts'])
AssertionError: 1680027559.5348852 is not None

----------------------------------------------------------------------
Ran 2 tests in 0.661s
```

After this change:

```
----------------------------------------------------------------------
Ran 2 tests in 0.621s

OK
```